#!/bin/bash

echo "Primes up to 100k ML"
time ./100kPrimes > JUNK100K
echo "Primes up to 500k ML"
time ./500KPrimes > JUNK500K
echo "Primes up to 1 million ML"
time ./1milPrimes > JUNK1M
echo "Primes up to 10 million ML" 
time ./10milPrimes > JUNK10M
echo "Primes up to 100 million ML" 
time ./100milPrimes > JUNK100M
echo "Primes up to 1B ML" 
time ./1BPrimes > JUNK1B

