#!/bin/bash
echo "Primes up to 100k 1 Thread"
time ./primesMT -u 100000 -t 1 > JUNK100K1T
echo "Primes up to 500K 1 Thread"
time ./primesMT -u 500000 -t 1 > JUNK500k1T
echo "Primes up to 1mil 1 Thread"
time ./primesMT -u 1000000 -t 1 > JUNK1M1T
echo "Primes up to 1mil 10 Threads"
time ./primesMT -u 1000000 -t 10 > JUNK1M10T
echo "Primes up to 10mil 10 Threads"
time ./primesMT -u 10000000 -t 10 > JUNK10M10T
echo "Primes up to 100mil 10 Threads"
time ./primesMT -u 100000000 -t 10 > JUNK100M10T
